### ISSUE TITLE
nodejs 7 可以开启支持async和await的模式了

### ISSUE THREAD

**Issue by Molunerfinn** [BUPT-HJM/vue-blog#1]
nodejs 7.0.0 开始已经支持使用 --harmony-async-await 选项来开启async 和 await功能

可以不必用babel转了。后端koa直接用node写async和await原生支持。前端用vue-cli的webpack模板的es6足够了

**Comment by BUPT-HJM** [comment]
今天我也刚看到node7居然可以，我试试看~😄谢谢皮蛋
