### ISSUE TITLE
will vue-blog supports docker?

### ISSUE THREAD

**Issue by litt1e-p** [BUPT-HJM/vue-blog#11]
will vue-blog supports docker? Thanks.

**Comment by BUPT-HJM** [comment]
vue-blog will supports docker soon.

**Comment by BUPT-HJM** [comment]
I'm sorry for spending too long time on this feature because of other things.
But now vue-blog supports docker.(see https://github.com/BUPT-HJM/vue-blog/commits/master)
You can get more info about it from README.md.

**Comment by litt1e-p** [comment]
@BUPT-HJM that is great! 🎉
