### ISSUE TITLE
你好,关于服务器渲染的问题

### ISSUE THREAD

**Issue by beat10086** [BUPT-HJM/vue-blog#12]
你好，老师
<music-list
                       @bankDetail="bankDetail"
                       :platform="perkList.platform"
                       :data="perkList.songList">
</music-list>
如果父组件里面，怎么把子组件的dom的节点渲染到源代码上,这个问题，怎么处理，非常感谢！

**Comment by BUPT-HJM** [comment]
不是很理解，用的是本项目吗？都是可以渲染出来的，只要写好preFetch就行

**Comment by beat10086** [comment]
不是，本项目,就是子组件dom的不能渲染，出来

**Comment by beat10086** [comment]
老师，就是这个子组件的dom,不能在源码显示,还是marked那个包是干什么用的，谢谢老师
------------------ 原始邮件 ------------------
发件人: "HJM";<notifications@github.com>;
发送时间: 2017年11月9日(星期四) 中午1:57
收件人: "BUPT-HJM/vue-blog"<vue-blog@noreply.github.com>;
抄送: "beat.茶末"<616576976@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BUPT-HJM/vue-blog] 你好,关于服务器渲染的问题 (#12)




不是很理解，用的是本项目吗？都是可以渲染出来的，只要写好preFetch就行

**Comment by BUPT-HJM** [comment]
这个子组件？希望可以描述清楚点哈~vue-blog本项目展示front部分都是可以的

关于marked就是[https://github.com/chjj/marked](https://github.com/chjj/marked)，用于markdown渲染的
> A full-featured markdown parser and compiler, written in JavaScript. Built for speed.

**Comment by beat10086** [comment]
老师，可以加一个qq嘛，邮件不好说





------------------ 原始邮件 ------------------
发件人: "HJM";<notifications@github.com>;
发送时间: 2017年11月9日(星期四) 下午2:07
收件人: "BUPT-HJM/vue-blog"<vue-blog@noreply.github.com>;
抄送: "beat.茶末"<616576976@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BUPT-HJM/vue-blog] 你好,关于服务器渲染的问题 (#12)




这个子组件？希望可以描述清楚点哈~vue-blog本项目展示front部分都是可以的
 
关于marked就是https://github.com/chjj/marked，用于markdown渲染的
  
A full-featured markdown parser and compiler, written in JavaScript. Built for speed.

**Comment by BUPT-HJM** [comment]
OK，https://github.com/BUPT-HJM   中看到邮箱地址便是

**Comment by beat10086** [comment]
老师，就是关于这个列表，是通过ajax请求的,通过子组件来写,这个dom,不能渲染到源代码上




------------------ 原始邮件 ------------------
发件人: "HJM";<notifications@github.com>;
发送时间: 2017年11月9日(星期四) 下午2:07
收件人: "BUPT-HJM/vue-blog"<vue-blog@noreply.github.com>;
抄送: "beat.茶末"<616576976@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [BUPT-HJM/vue-blog] 你好,关于服务器渲染的问题 (#12)




这个子组件？希望可以描述清楚点哈~vue-blog本项目展示front部分都是可以的
 
关于marked就是https://github.com/chjj/marked，用于markdown渲染的
  
A full-featured markdown parser and compiler, written in JavaScript. Built for speed.
