### ISSUE TITLE
ie浏览器下页面报错（ie11）

### ISSUE THREAD

**Issue by elvis7758258** [BUPT-HJM/vue-blog#14]
您好，最近下了您的代码下来跑了下，发现在ie下程序出错，浏览器版本为ie11，麻烦有时间帮忙看下问题出在哪里了，谢谢，以下为报错的截图：
![image](https://user-images.githubusercontent.com/27201833/34325431-57183ac6-e8cc-11e7-8a50-dba024f9d90c.png)

![image](https://user-images.githubusercontent.com/27201833/34325436-7888944e-e8cc-11e7-8047-f89691aab164.png)

**Comment by BUPT-HJM** [comment]
https://github.com/glenjamin/webpack-hot-middleware/issues/53
由于webpack-hot-middleware/client用到EventSource，需要对IE加polyfill (其实开发环境还是建议使用chrome)

已修复：https://github.com/BUPT-HJM/vue-blog/commit/7218b2d52ced3b8d75ab6df21f05f0538e21a634
可以试试~

**Comment by elvis7758258** [comment]
@BUPT-HJM 还是不行呢

**Comment by BUPT-HJM** [comment]
你需要pull新代码，重新install

**Comment by BUPT-HJM** [comment]
发现问题了
- strip-ansi降级到@3.0.1(https://github.com/zeit/next.js/issues/2747)
- 增加babel-polyfill

已更新修复，具体可以看 http://imhjm.com/admin 下在IE的表现
