### ISSUE TITLE
token问题

### ISSUE THREAD

**Issue by zsg857981535** [BUPT-HJM/vue-blog#16]
请问ssr 你的token存到哪里的? 因为在client和server调用接口都要用到, 所以放到localStorag里server取不到,放到cookie里client也取不到

**Comment by zsg857981535** [comment]
哦哦,我现在困扰这个权限的问题,用token的话改放在哪里呢?讨论下

**Comment by BUPT-HJM** [comment]
参考如下
https://github.com/vuejs/vue-hackernews-2.0/issues/183
https://github.com/vuejs/vue-hackernews-2.0/issues/272

**Comment by zsg857981535** [comment]
这个issue之前看到,说实话,不太理解 (*^▽^*)

**Comment by BUPT-HJM** [comment]
首先会有个login页面，这个不需要鉴权，然后点击登录，服务端鉴权，返回客户端凭证，客户端存储即可。

之后假如用到SSR刷新，客户端应该往服务端发送一个本地存储的用户凭证，然后服务端渲染页面的时候，判断凭证是否生效，未登录则再跳转到login页面，登录则正常返回，具体的服务端router push在这里操作（https://github.com/BUPT-HJM/vue-blog/blob/master/client/src/modules/front/entry-server.js#L10）

其实 https://github.com/vuejs/vue-hackernews-2.0/issues/183 中dmitry7887已经讲得挺清楚的了哈~

**Comment by zsg857981535** [comment]
恩,谢谢,好像明白了,我再消化一下
