### ISSUE TITLE
重构

### ISSUE THREAD

**Issue by Hideer** [BUPT-HJM/vue-blog#17]
你好，我正在学习ssr以及koa2想，通过您的项目一手一步步的搭建，但是在书写启动服务的入口文件的时候，有些蒙了，比如环境的判断
![image](https://user-images.githubusercontent.com/31301552/37011646-ff616ef4-212b-11e8-8ec2-88fb05aed994.png)
书写到这里的时候，我发现，可能自己还没弄懂您整个项目的构建过程，所以，你方便的话，可以和我说下您在搭建这个项目的时候整个构建思路么，以及架构的流程。Thanks♪(･ω･)ﾉ

**Comment by Hideer** [comment]
![image](https://user-images.githubusercontent.com/31301552/37081067-44541366-2223-11e8-95fb-14efec99c0cb.png)
请问下您这里作用是什么意思。。。。

**Comment by BUPT-HJM** [comment]
不好意思，最近比较忙，忘记回了

第一个截图是生产环境和开发环境的区别，生产环境直接读取硬盘文件，开发环境读取的是内存，有利于快速文件重建，具体可以了解下hot/dev middleware的作用

第二个截图第一行是暴露数据给HTML，使得客户端可以拿到服务端已经取到的数据，第二行我里面没有加注释，因为这里我取到了所有文章的内容，我不想全部塞到页面中，因为这样会使HTML太大，影响首屏，所以我把它们设置为空了

**Comment by Hideer** [comment]
好的，上面的问题，基本能弄清楚了；

在我根据您的架构搭建第一个页面的时候，发现只有当页面刷新的时候是直接服务端返回html的数据，就是俗称的服务端渲染，但是当我们通过vue中路由进行页面的变化的时候，发现此时服务端并没有返回整个html文件，这让我对服务端渲染的定义有些模糊了，既然只是首次刷新的话，我们完全可以使用预渲染的方式，何必使用服务端渲染呢，您可以给我分享下您的理解么？

最后一个问题:由于上面的问题我都无法判断一个页面是否是服务端渲染的，您知道怎么判断么？

**Comment by BUPT-HJM** [comment]
具体可以看这里[服务端渲染的优劣以及服务端渲染VS预渲染](https://ssr.vuejs.org/zh/)
> 如果你调研服务器端渲染(SSR)只是用来改善少数营销页面（例如 /, /about, /contact 等）的 SEO，那么你可能需要预渲染。无需使用 web 服务器实时动态编译 HTML，而是使用预渲染方式，在构建时(build time)简单地生成针对特定路由的静态 HTML 文件。优点是设置预渲染更简单，并可以将你的前端作为一个完全静态的站点。

至于判断是不是服务端渲染，可以从network看返回的内容是不是都有内容，而不是js置入，至于与预渲染对比的话，其实服务端渲染会往window中放入一些数据让前端可以取到，用来同步服务端与前端，可能可以通过这点来判断。
