### ISSUE TITLE
打包的时候出现的问题

### ISSUE THREAD

**Issue by Hideer** [BUPT-HJM/vue-blog#18]
```
ERROR in modules/admin.06a91d44.min.js from UglifyJs
Unexpected token: operator (>) [modules/admin.06a91d44.min.js:68,23]

ERROR in modules/front.d96e9ae6.min.js from UglifyJs
Name expected [modules/front.d96e9ae6.min.js:46,6]
```

- webpack的配置，和您的是一样的但是构建的shih时候出现这个问题。。。。
> 这是在生产环境下，出现的问题，开发环境没问题，修改UglifyJs插件后虽然构建了但是页面保存提示意外的< 并且图片资源无法显示。。。。

**Comment by BUPT-HJM** [comment]
我这里是没问题，估计和环境或者webpack有关系，webpack版本？node、npm版本？

**Comment by Hideer** [comment]
上面的问题，我好想发现了是index.js中的书写错误，但是今天写接口的使用使用axios进行mock数据请求的时候，发现，请求道德并不是自己模拟的json数据，而是index.html首页，然后我回到您的项目，发现是同样的问题：
如下
![image](https://user-images.githubusercontent.com/31301552/37945522-3a78699c-31b3-11e8-9def-b44dfe8160e7.png)
我在一个后端的页面进行数据请求的使用，并没有报接口的问题，路径什么的是对的，但是
![image](https://user-images.githubusercontent.com/31301552/37945559-682578da-31b3-11e8-9825-e115d48df4c0.png)

首先这里的文件类型不对
并且返回的数据也不对（我请求的路径是正确的）
![image](https://user-images.githubusercontent.com/31301552/37945592-87f3df62-31b3-11e8-8ff7-435d3a9eec86.png)

刚开始的时候我怀疑是和index中 的admin路径的过滤有关
![image](https://user-images.githubusercontent.com/31301552/37945638-b5f03942-31b3-11e8-82b4-dc2e05a7c358.png)

当我仔细看这个的时候，发现这个主要解决的是history的问题，刷新页面丢失的问题，好像问题也并不是这个。。。

您能给我一些帮助么

**Comment by BUPT-HJM** [comment]
https://github.com/BUPT-HJM/vue-blog/blob/master/server/index.js#L34

因为没有请求到，所以走后面的逻辑了，我的静态资源是位于'./client/static'里的

**Comment by Hideer** [comment]
我找到了原因，我请求的要经过koa的服务，自然需要在koa中设置专门的api路由，因为，我们整个页面的服务是基于koa它起的服务，尽管，我们是的后台界面是不通过后端渲染的，但是服务是基于koa 的，并不像我之前的项目，前台就是前台的服务，nodejs就是node的服务，

不知道我这样理解对不对，还有就是宁的这个static是没有资源的

**Comment by BUPT-HJM** [comment]
嗯嗯
