### ISSUE TITLE
关于使用jwt的一些问题

### ISSUE THREAD

**Issue by Hideer** [BUPT-HJM/vue-blog#22]
- 我同样在项目中使用了jwt进行登入校验，但是发现一个问题，就是由于后台和前台使用的是一套的node接口；这样我在进入前台进行接口请求的时候会被同样执行jwt的token的验证，其实这是不必要的，我开始想到的是对前台和后台请求同一套接口的时候进行传递一个特定参数进行有效的区别，但是这样的方式特别低效,请问您是怎么解决这个问题的呢

**Comment by BUPT-HJM** [comment]
不是所有的接口都需要鉴权的，像那种前台也要使用的是不需要鉴权的

**Comment by Hideer** [comment]
我想你可能还没有仔细看我的提问，开发过程中就是遇到了前台不需要鉴权，但是前台和后台要是使用的都是一个接口的话，怎么处理这样的情况，有什么好的方法

**Comment by BUPT-HJM** [comment]
我的意思就是后台用这个接口为何还要鉴权的意思

所以要么把这个接口鉴权去掉了，要么加参数，加接口之类的

**Comment by Hideer** [comment]
我的理解是后台需要鉴权，前台仅仅只是展示，不要用到jwt，后台因为要对文章进行写的操作等需要鉴权，您给我的解决方法和我目前想的基本一致（加参数判断是前台还是后台请求的接口），这样感觉有些不优雅，我再想想

**Comment by BUPT-HJM** [comment]
恩恩，写的操作要鉴权，展示list的接口是不需要的，没有特殊的需求，可以把这个接口的鉴权去掉。
后台用的接口也不是所有都需要鉴权的。
