### ISSUE TITLE
one question:

### ISSUE THREAD

**Issue by hudyseu** [BUPT-HJM/vue-blog#23]
看了博主的文章之后，也有了准备着手搭个自己的博客的冲动😂。还有一个问题，就是博客没有评论系统。顺便请问博主，文章里面那个关于博客的系统结构图是用什么软件画的呢？

**Comment by BUPT-HJM** [comment]
有评论系统，不过是disqus，不翻墙加载不出来的哈~

至于图的话，看这个 https://github.com/BUPT-HJM/vue-blog/issues/2
