### ISSUE TITLE
如何添加新的博客？

### ISSUE THREAD

**Issue by serend1p1ty** [BUPT-HJM/vue-blog#26]
很棒的项目。
npm run dev之后界面空空如也，如何写新的博客呢？
前端小白一枚。。

**Comment by serend1p1ty** [comment]
知道了，打开`http://localhost:8889/admin`这个网址即可，账号是admin，密码是password。
但是还有一个问题，为什么写文章的时候一直提示摘要不能为空？什么是摘要啊？

**Comment by BUPT-HJM** [comment]
不好意思，没有及时回复
`<!--more-->` 前面是摘要，文章真正对外展示的时候会展示摘要+继续阅读...

**Comment by serend1p1ty** [comment]
哦哦，知道了，感谢回复！
