### ISSUE TITLE
楼主请教你PC和移动端自适应问题!

### ISSUE THREAD

**Issue by Foreverofh** [BUPT-HJM/vue-blog#4]
楼主是用flex布局吗?开发是先按照PC来做? 之后@media来判断控制样式和宽度吗?

**Comment by BUPT-HJM** [comment]
有没有用flex你直接看代码就知道了(我这里没用)，如果pc和移动端是一套代码，刚开始就得想好样式了，哪些在移动端不要哪些要哪些隐藏之类的
我是直接使用`<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,minimal-ui">`
加@media适配的

网上有很多适配方案，rem、flex、百分比等等，可以多了解看看
可以看下面这个
[移动端适配方案(下) ](https://github.com/riskers/blog/issues/18)
