### ISSUE TITLE
'\"node --harmony\"' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by k55783637** [BUPT-HJM/vue-blog#8]
![default](https://user-images.githubusercontent.com/16603099/30154861-c36c9246-93ed-11e7-8f56-b0c842f2c770.png)

**Comment by BUPT-HJM** [comment]
直接`node --harmony server/start.js`有问题吗？
如果有问题，可以看下node版本是否过低，至少使用6以上的
